name: Profile Automation

# push, 수동 실행, 그리고 두 가지 스케줄(cron)을 모두 트리거로 걸어둡니다.
on:
  push:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: '0 18 * * *'

env:
  TIMEZONE: Asia/Seoul   
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@v1.2.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID:  ${{ secrets.GIST_ID }}
          TIMEZONE: ${{ env.TIMEZONE }}

  generate-3d-grass:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate 3D grass
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}   
          USERNAME:       ${{ github.actor }}

      - name: Commit & Push 3D grass
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A .
          git commit -m "chore: update 3D grass"
          git push
