name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME:     ${{ github.repository_owner }}

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name  "kim-1210"
          git config user.email "zxmzxm1324@gmail.com"
          git remote set-url origin https://github.com/kim-1210/kim-1210.git
          git add -A .
          git commit -m "generated" || echo "No changes"
          git push https://$GITHUB_TOKEN@github.com/kim-1210/kim-1210.git
